# Generated by Django 4.0.3 on 2022-03-30 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_address_author_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postl_code',
            new_name='postal_code',
        ),
    ]
